[workspace]
authors = ["jamisonpeebles <jamisonpeebles@live.com>"]
channels = ["conda-forge"]
name = "MonteCarloIntegration"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
logNormal = "python -m src.logNormalMonteCarlo"
scaled = "python -m src.logNormal_scaled"

[dependencies]
python = ">=3.12, <3.13"
numpy = "*"
matplotlib = "*"
pandas = "*"
python-dateutil = "*"
scipy = "*"
